autoload -U colors
autoload -U compinit
autoload -U edit-command-line

# Options, list all: $ man zshoptions
setopt APPEND_HISTORY
setopt CORRECT
setopt AUTO_LIST
setopt NO_BEEP
setopt COMPLETE_IN_WORD

colors
compinit

# Oh-my-posh prompt
# https://github.com/JanDeDobbeleer/oh-my-posh/tree/main/themes
THEME_NAME="kali"
eval "$(oh-my-posh init zsh --config $(brew --prefix oh-my-posh)/themes/$THEME_NAME.omp.json)"

# Install directory
export DOTFILES="$HOME/.dotfiles"

# Source scripts
source $DOTFILES/system/aliases.zsh
source $DOTFILES/system/exports.zsh 
