#!/bin/zsh
export FPATH="/opt/homebrew/share/zsh/site-functions:$FPATH"

export EDITOR="vim"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export MANPAGER="less -X"

# CMake
export CXX="/usr/bin/clang++"
export CC="/usr/bin/clang"

# Emscripten
export EMSDK_QUIET=1